### ISSUE TITLE
添加欢迎内容分群管理

### ISSUE THREAD

**Issue by Initial-heart-1** [Colter23/simple-welcome-plugin#1]
多数情况下，每个群需要的欢迎消息内容都是不一样的，直接全局统一会比较尴尬
可以做成类似向导的形式，对终端用户会更友好
同理，也需要将“允许配置欢迎内容”放进 mirai 权限管理中，方便直接让全部的群聊管理员自主配置
当然，出于安全性考虑，通过权限管理系统取得的权限应该只能配置所在群，或者将可以配置所有群和仅能配置所在群的权限分开（如果 mirai 已经考虑到这部分那就当我没说，但应该是没有的）

**Comment by Colter23** [comment]
这插件也算半弃坑了，这个版本还是只是临时用的，新的我这边写的差不多了，不过还没放出来（包括的说的每个群不同的欢迎语（不过这个插件好久没动他了，最后一些有点懒得写了（
